name: movielicious
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  retrofit: ^4.0.3
  dio: ^5.3.3
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  fpdart: ^1.1.0
  carousel_slider: ^4.2.1
  bloc_concurrency: ^0.2.3
  stream_transform: ^2.1.0
  gap: ^3.0.1
  expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  retrofit_generator: ^8.0.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  http_mock_adapter: ^0.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
