name: movielicious
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  retrofit: ^4.0.3
  dio: ^5.3.3
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  bloc_test: ^9.1.4
  retrofit_generator: ^8.0.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  http_mock_adapter: ^0.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
