name: Add labels to PR
run-name: Add labels to ${{ github.event.pull_request.head.ref }}

on:
  issues:
  pull_request:
    branches: [develop]

permissions:
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest


    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Add labels to PR
      uses: srvaroa/labeler@master
      with:
        config_path: .github/labeler-config.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}